angular
  .module('themis', [
    'templates-app',
    'templates-common',
    'themis.login',
    'themis.home',
    'themis.enqueteurs',
    'themis.status',
    'themis.corps',
    'themis.items',
    'themis.missions',
    'themis.tribunals',
    'themis.clerks',
    'themis.departments',
    'themis.prosecutors',
    'themis.ranks',
    'themis.courts',
    'themis.itemMissions',
    'ui.router',
    'ngSanitize',
    'angularUtils.directives.dirPagination'
  ]); 
